### PR TITLE
works even better

### PR DESCRIPTION
**Pull request by sjohn198**
Got add orders working with large products and it wipes after a submit. Manage orders now displays orders and has padding on the side.

### CODE REVIEW

**Comment by RayLui2** [comment]
I think the feature where the order wipes after it submits is very clean, functionality is great. Display looks great as well for displaying orders, great work Seth.

**Review by cmaloney111 — COMMENTED** [review]
Appreciate you adding the styling changes and fixing that bug with the large quantities. We should maybe separate our styles into different files since it's getting pretty large and definitely is not related to the navbar. Good job!

**Comment by jkalsi1** [comment]
Good work Seth. The styling changes look good, too!

**Review by jkalsi1 — COMMENTED** [review]
Good work Seth. The styling changes look good, too!

**Comment by BrawlPaul** [comment]
Looks good to me Seth! One thing I just thought of, do we want to have the frontend navigate to the manage orders page after submission? Not related to functionality, but could be worth discussing.

**Review by RayLui2 — COMMENTED** [review]
I think the feature where the order wipes after it submits is very clean, functionality is great. Display looks great as well for displaying orders, great work Seth.

**Pull request merged**
