### PR TITLE
Unit Testing

### PR DESCRIPTION
**Pull request by jkalsi1**
Test of Form.jsx in Form.spec.jsx

### CODE REVIEW

**Comment by RayLui2** [comment]
Good work testing form.jsx.

**Review by sjohn198 — COMMENTED** [review]
Form tests look great Jagen, thank you.

**Review by cmaloney111 — COMMENTED** [review]
Looks good! I wonder if we should add the .jsx.html files to our git ignore though, as well as other files related to coverage.

**Review by RayLui2 — COMMENTED** [review]
Good work testing form.jsx.

**Pull request merged**
