### PR TITLE
Editing Profile + Delete User Profile

### PR DESCRIPTION
**Pull request by BrawlPaul**
Functionality added so that profiles can be deleted and and bio and skills fields can be edited

### CODE REVIEW

**Review by cmaloney111 — COMMENTED** [review]
The new component and page look good. You just reminded me that we should ignore uploads though... my bad on that! Appreciate all your work on user authentication!

**Review by sjohn198 — COMMENTED** [review]
This looks great Ben. Thanks for ading this important feature.

**Comment by RayLui2** [comment]
Awesome work Ben, thank you.

**Review by jkalsi1 — COMMENTED** [review]
Cool Ben, looks good. Finally we can delete accounts!

**Pull request merged**
