### PR TITLE
Editing inventory page

### PR DESCRIPTION
**Pull request by RayLui2**
Changed the edit feature so that it actually edits specific products, and allowed backend to handle the editing correctly.

### CODE REVIEW

**Review by cmaloney111 — COMMENTED** [review]
nit: I think we are only using the button once, so may not need that general text feature. Regardless, good forward thinking.

Great job making editing working, LGTM!

**Review by sjohn198 — COMMENTED** [review]
Two routes look great and the addition of the button title was important.

**Comment by RayLui2** [comment]
> nit: I think we are only using the button once, so may not need that general text feature. Regardless, good forward thinking.
> 
> Great job making editing working, LGTM!

No worries, will keep that in mind. Was just looking ahead of time with the button.

**Comment by RayLui2** [comment]
> Two routes look great and the addition of the button title was important.

Thank you! Glad you are happy with the changes.

**Comment by jkalsi1** [comment]
Looks good Ray, nice work

**Review by jkalsi1 — COMMENTED** [review]
Looks good Ray, nice work.

**Comment by RayLui2** [comment]
> Looks good Ray, nice work.

Thank you Jagan.

**Comment by BrawlPaul** [comment]
Not much to comment. Looks like functionality works on my end! Thanks for all the hard work Ray.

**Pull request merged**
