### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by cmaloney111**
I changed the form and order form to contain the correct styling elements. I also added navbar styles for the buttons when hovering and padding. I changed the product page to correctly edit for all three fields in the back end (which involved adding a method to the product-service). Lastly, I made a small edit to the profile page to correctly display the profile picture.

The reason I made the styling changes is to have the style be consistent throughout the app (with consistent padding with the edges of the screen). I added the nav bar hovering element to improve the UI. I fixed a bug with the editing of a specific product that wouldn’t allow edits to work with only one field or two fields (it only worked with 3 before). I fixed the display of the profile picture to allow users to correctly see their profile picture when on the profile page (before it would not show.)

### CODE REVIEW

**Review by sjohn198 — COMMENTED** [review]
This changes look great Cameron! I especially like the styling changes. My only complaint is to maybe consider removing some of the testing print statements at some point in the future (e.g. the one's that say hi), but that's a super minor issue.

**Review by jkalsi1 — COMMENTED** [review]
Thanks for making style changes consistent Cam, they look good! The code you added is easily readable too, which I appreciate as a reviewer.

**Comment by RayLui2** [comment]
Styling changes look great on the website, good work Cameron. Navbar also functions really well, which I really like as well.

**Comment by BrawlPaul** [comment]
Looks fantastic Cameron! Our service feels much more cohesive with these changes

**Comment by cmaloney111** [comment]
> This changes look great Cameron! I especially like the styling changes. My only complaint is to maybe consider removing some of the testing print statements at some point in the future (e.g. the one's that say hi), but that's a super minor issue.

Good point Seth! Completely missed those.

**Review by RayLui2 — COMMENTED** [review]
Styling changes look great on the website, good work Cameron. Navbar also functions really well, which I really like as well.

**Pull request merged**
